### ISSUE TITLE
Programming 

### ISSUE THREAD

**Issue by theorgBigBoss** [McHauge/OpenCorsairLighting#2]
Hi
What is "USB Programming Enable" and "Programming Header" in the board?
is it possible to upload the code with normal USB? or i should upload the code using this headers?

**Comment by McHauge** [comment]
Hi, the "USB Programming Enable" header is for use with other Atmel programmers, if you need to recover a bricked device. 

When using Arduino you will need to use the "Programming header" also called an "ISP port" for burning the bootloader (this can be done with another Arduino or as I did with a TinyUSB programmer from Adafrouit), after that, you can use USB to program the device like any other Arduino, if something fails, then just re-install the bootloader again.

**Comment by theorgBigBoss** [comment]
thanks for your answer
i want upload Legion2 code once and then just use for i,Cue
so if i burn bootloader with programmer ,can i remove "USB Programming Enable" and "Programming Header" safely?

**Comment by McHauge** [comment]
yes, burn the bootloader and flash the firmware. the "USB Programming Enable" pin header is not required, I just added it if someone needed it, it can be ignored for normal use
